"""initial schema

Revision ID: 4ff98a17b65b
Revises: 
Create Date: 2026-08-13 08:22:58.475009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff98a17b65b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('recall_bot_id', sa.String(length=255), nullable=True),
    sa.Column('recall_meeting_id', sa.String(length=255), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_recall_bot_id'), 'meetings', ['recall_bot_id'], unique=True)
    op.create_index(op.f('ix_meetings_recall_meeting_id'), 'meetings', ['recall_meeting_id'], unique=True)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_transcript_ids', sa.JSON(), nullable=True),
    sa.Column('jira_issue_id', sa.String(length=255), nullable=True),
    sa.Column('jira_issue_key', sa.String(length=255), nullable=True),
    sa.Column('notion_page_id', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('decision_maker', sa.String(length=255), nullable=True),
    sa.Column('stakeholders', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_transcript_ids', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_meeting_id'), 'decisions', ['meeting_id'], unique=False)
    op.create_table('meeting_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=255), nullable=True),
    sa.Column('shared_links', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_summaries_id'), 'meeting_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_meeting_id'), 'meeting_summaries', ['meeting_id'], unique=False)
    op.create_table('open_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('asked_by', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_transcript_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_questions_id'), 'open_questions', ['id'], unique=False)
    op.create_index(op.f('ix_open_questions_meeting_id'), 'open_questions', ['meeting_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('mitigation_suggested', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_transcript_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_meeting_id'), 'risks', ['meeting_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_name', sa.String(length=255), nullable=True),
    sa.Column('speaker_id', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('processed_by_agent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_chunks_id'), 'transcript_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_meeting_id'), 'transcript_chunks', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_chunks_meeting_id'), table_name='transcript_chunks')
    op.drop_index(op.f('ix_transcript_chunks_id'), table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_risks_meeting_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_open_questions_meeting_id'), table_name='open_questions')
    op.drop_index(op.f('ix_open_questions_id'), table_name='open_questions')
    op.drop_table('open_questions')
    op.drop_index(op.f('ix_meeting_summaries_meeting_id'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_meeting_summaries_id'), table_name='meeting_summaries')
    op.drop_table('meeting_summaries')
    op.drop_index(op.f('ix_decisions_meeting_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_meetings_recall_meeting_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_recall_bot_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
